language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - pwd
  - pip install -r requirements.txt
  - export LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH

script:
  - python setup.py pytest
